version = 0.1

[default.deploy.parameters]
stack_name = "aws-eventdna-app"
resolve_s3 = true
s3_prefix = "aws-eventdna-app"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-north-1"
